### ISSUE TITLE
Почему то не отвечает botanio при работе с node.js

### ISSUE THREAD

**Issue by SerjoPepper** [botanio/sdk#20]
error: null
response.statusCode: 500
matchmaker-24 response.statusText: undefined
matchmaker-24 error: Error: connect ETIMEDOUT
matchmaker-24 uncaughtException: TypeError: Cannot read property 'statusCode' of undefined, TypeError: Cannot read property 'statusCode' of undefined
  at Request._callback (/home/www/matchmaker/node_modules/botanio/botan.js:23:71)
  at self.callback (/home/www/matchmaker/node_modules/botanio/node_modules/request/request.js:354:22)
  at Request.emit (events.js:107:17)
  at Request.onRequestError (/home/www/matchmaker/node_modules/botanio/node_modules/request/request.js:1011:8)
  at ClientRequest.emit (events.js:107:17)
  at TLSSocket.socketErrorListener (_http_client.js:271:9)
  at TLSSocket.emit (events.js:129:20)
  at net.js:459:14
  at process._tickCallback (node.js:355:11)

**Comment by ollmer** [comment]
У нас была небольшая деградация производительности, время ответа выросло, могло отваливаться по таймауту. Проверьте сейчас, должно работать.

**Comment by ihoru** [comment]
^_^
