### ISSUE TITLE
statusCode error

### ISSUE THREAD

**Issue by dcsan** [botanio/sdk#36]
I see this in my logs when i have a service pinging my apps to check they're alive.
perhaps there is no body in the request or something that is causing, looks like the error is deep  in your code.

```
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/root/www/newtopic_bot/node_modules/botanio/botan.js:23:71)
    at self.callback (/root/www/newtopic_bot/node_modules/botanio/node_modules/request/request.js:354:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/root/www/newtopic_bot/node_modules/botanio/node_modules/request/request.js:1011:8)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketOnEnd (_http_client.js:300:9)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by strikeentco** [comment]
It seems you are using an outdated version of the package. Just update the package with following command:
```sh
npm update botanio
```

**Comment by dcsan** [comment]
├─┬ botanio@0.0.5

?

**Comment by strikeentco** [comment]
23rd line with statusCode no longer exist (4407570), so now all should be fine :)
